Introduction to pandas/ importing pandas and io libraries 

In [40]:
import pandas as pd
import io

First function in pandas/ creating a table using cvs file

In [12]:
csv = """index,a,b
0,hello,pandas"""
pd.read_csv(io.StringIO(csv), index_col = False)



index      a       b
0      0  hello  pandas

In [8]:
pd.read_csv('test.csv')

index      a       b
0      0  hello  pandas

Creating a basic dictionary and creating Data framework in pandas

In [11]:
data = {'weekday': ['Sun','Sat','Mon','Wed'],
        'city': ['Almaty','NY','LA','Astana'],
        'visitors': [200, 139, 36, 45]}
users = pd.DataFrame(data)
users


weekday    city  visitors
0     Sun  Almaty       200
1     Sat      NY       139
2     Mon      LA        36
3     Wed  Astana        45

Creatind simple lists and making a dictionary, while using zip function that connects all lists together.

In [13]:
cities = ['Almaty','NY','LA','Astana']
weekday = ['Sun','Sat','Mon','Wed']
visitors = [200, 139, 36, 45]

list_labels = ['cities','weekday','visitors']
list_cols = [cities,weekday,visitors]

dict(zip(list_labels,list_cols))

{'cities': ['Almaty', 'NY', 'LA', 'Astana'],
 'weekday': ['Sun', 'Sat', 'Mon', 'Wed'],
 'visitors': [200, 139, 36, 45]}

Adding a new column to our Df(data framework)

In [16]:
users['purchase'] = [20, 33, 12, 8]

In [17]:
users

weekday    city  visitors  purchase
0     Sun  Almaty       200        20
1     Sat      NY       139        33
2     Mon      LA        36        12
3     Wed  Astana        45         8

Changing the titles of the rows by using the next function:

In [18]:
users.index = ['a','b','c','d']

In [19]:
users

weekday    city  visitors  purchase
a     Sun  Almaty       200        20
b     Sat      NY       139        33
c     Mon      LA        36        12
d     Wed  Astana        45         8

Creating another Df/ using new functions head/tail to represent our df in a certain range

In [24]:
one = {'age': [5,7,9,10,15,18,20,22,24,26,28,30,32,34,36,38,40]}
df = pd.DataFrame(one)
df.tail()


age
12   32
13   34
14   36
15   38
16   40

Getting an information about our Df

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     17 non-null     int64
dtypes: int64(1)
memory usage: 264.0 bytes


Uing new function to represent our df in a certain range

In [29]:
df.iloc[10:15]

age
10   28
11   30
12   32
13   34
14   36

Using names =, heads = we can change our column titles.

In [30]:
col_names = ['Number','Headword','Nextword']
pd.read_csv('test.csv', names = col_names)

Number Headword Nextword
0  index        a        b
1      0    hello   pandas

Homework

1. Creating my own Df with csv file

In [5]:
data_2 = pd.read_csv('sense.csv')
df_2 = pd.DataFrame(data_2)
df_2

Number   Students name  Marks for the 1st semester
0       1     Alex Martin                           A
1       2    Amanda Guter                          A+
2       3      Aaron Hank                          B+
3       4    Abbey Edward                          A+
4       5      Acton John                           B
5       6   Babbit Milton                           B
6       7   Caesar Julius                           A
7       8   Cameron Julia                           C
8       9    Fakes Dennis                          C+
9      10      Fawkes Guy                           F

Trying various functions with csv file/ 1) deleting unnecessary rows

In [7]:
df_2.drop('Number', axis = 1, inplace = True)
df_2

Students name  Marks for the 1st semester
0     Alex Martin                           A
1    Amanda Guter                          A+
2      Aaron Hank                          B+
3    Abbey Edward                          A+
4      Acton John                           B
5   Babbit Milton                           B
6   Caesar Julius                           A
7   Cameron Julia                           C
8    Fakes Dennis                          C+
9      Fawkes Guy                           F

2) adding new rows

In [42]:
df_2.loc[1] = ['Helena Shmidt', 'B+']

In [43]:
df_2

Students name  Marks for the 1st semester
0     Alex Martin                           A
1   Helena Shmidt                          B+
2      Aaron Hank                          B+
3    Abbey Edward                          A+
4      Acton John                           B
5   Babbit Milton                           B
6   Caesar Julius                           A
7   Cameron Julia                           C
8    Fakes Dennis                          C+
9      Fawkes Guy                           F

Third lesson/ learning some numpy techniques 

In [9]:
import numpy as np
array = np.array([2,3,4])

In [10]:
array >= 4

array([False, False,  True])

In [11]:
array[1]

3

In [12]:
array[array >= 4]

array([4])

In [13]:
list1 = [3,2,4]
list1 + list1


[3, 2, 4, 3, 2, 4]

In [15]:
array1 = np.array([[2,3,4], [5,6,7]])

In [18]:
array1[:,0]

array([2, 5])

In [23]:
array1[:,2:3]


array([[4],
       [7]])

In [26]:
array2 = np.array([8, 9, 10])
np.row_stack((array1, array2))
#np.column_stack(())

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Pandas

In [33]:
data3 = pd.read_csv('sense.csv')
data3[' Students name']

0       Alex Martin
1      Amanda Guter
2        Aaron Hank
3      Abbey Edward
4        Acton John
5     Babbit Milton
6     Caesar Julius
7     Cameron Julia
8      Fakes Dennis
9        Fawkes Guy
Name:  Students name, dtype: object

In [34]:
type(3)

int

In [35]:
type(data3[' Students name'])

pandas.core.series.Series

In [36]:
data3[' Students name'].values

array([' Alex Martin', ' Amanda Guter', ' Aaron Hank', ' Abbey Edward',
       ' Acton John', ' Babbit Milton', ' Caesar Julius',
       ' Cameron Julia', ' Fakes Dennis', ' Fawkes Guy'], dtype=object)

In [37]:
np.array([4,5,6])

array([4, 5, 6])

Creating new csv file

In [38]:
data3.to_csv('newfile.csv')

In [39]:
data3.to_excel('file2.xlsx')

In [59]:
df3 = pd.read_csv('flie3.csv', delimiter = '\d+')

C:\Users\Raihan\anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [61]:
df3

Index      a       b
0  Jack  Hello  pandas